apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: "2023-11-07T18:53:31Z"
  name: argocd-manager-role-binding
  namespace: argocd
  resourceVersion: "188973"
  uid: 01321ae9-9766-4fd8-b00f-0672e5fbd9b2
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argocd-manager-role
subjects:
- kind: ServiceAccount
  name: argocd-manager
  namespace: argocd
