apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"Role","metadata":{"annotations":{},"labels":{"app.kubernetes.io/component":"notifications-controller","app.kubernetes.io/name":"argocd-notifications-controller","app.kubernetes.io/part-of":"argocd"},"name":"argocd-notifications-controller","namespace":"argocd"},"rules":[{"apiGroups":["argoproj.io"],"resources":["applications","appprojects"],"verbs":["get","list","watch","update","patch"]},{"apiGroups":[""],"resources":["configmaps","secrets"],"verbs":["list","watch"]},{"apiGroups":[""],"resourceNames":["argocd-notifications-cm"],"resources":["configmaps"],"verbs":["get"]},{"apiGroups":[""],"resourceNames":["argocd-notifications-secret"],"resources":["secrets"],"verbs":["get"]}]}
  creationTimestamp: "2023-11-07T19:26:03Z"
  labels:
    app.kubernetes.io/component: notifications-controller
    app.kubernetes.io/name: argocd-notifications-controller
    app.kubernetes.io/part-of: argocd
  name: argocd-notifications-controller
  namespace: argocd
  resourceVersion: "193244"
  uid: 5a93ebfe-8300-4deb-8401-aebe3fe3e05b
rules:
- apiGroups:
  - argoproj.io
  resources:
  - applications
  - appprojects
  verbs:
  - get
  - list
  - watch
  - update
  - patch
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs:
  - list
  - watch
- apiGroups:
  - ""
  resourceNames:
  - argocd-notifications-cm
  resources:
  - configmaps
  verbs:
  - get
- apiGroups:
  - ""
  resourceNames:
  - argocd-notifications-secret
  resources:
  - secrets
  verbs:
  - get
