apiVersion: v1
data:
  configManagementPlugins: |
    - name: argocd-vault-plugin-helm
      init:
        command: [sh, -c]
        args: ["helm dependency build"]
      generate:
        command: ["sh", "-c"]
        args: ["helm template $ARGOCD_APP_NAME -n $ARGOCD_APP_NAMESPACE ${ARGOCD_ENV_helm_args} . | argocd-vault-plugin generate -"]
  resource.inclusions: "- apiGroups:\n  - \"apps\"\n  kinds:\n  - Deployment\n  clusters:\n
    \ - \"*\"\n- apiGroups:\n  - \"networking\"\n  kinds:\n  - \"Ingress\"\n  clusters:\n
    \ - \"*\"\n- apiGroups:\n  - \"networking.k8s.io\"\n  kinds:\n  - \"Ingress\"\n
    \ clusters:\n  - \"*\"      \n- apiGroups:\n  - \"argoproj.io\"\n  kinds:\n  -
    \"Rollout\"\n  clusters:\n  - \"*\"      \n- apiGroups:\n  - \"*\"\n  kinds:\n
    \ - \"Service\"\n  - \"Pod\"\n  - \"ConfigMap\"\n  - \"Secret\"\n  clusters:\n
    \ - \"*\"      \n"
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"resource.inclusions":"- apiGroups:\n  - \"apps\"\n  kinds:\n  - Deployment\n  clusters:\n  - \"*\"\n- apiGroups:\n  - \"networking\"\n  kinds:\n  - \"Ingress\"\n  clusters:\n  - \"*\"\n- apiGroups:\n  - \"*\"\n  kinds:\n  - \"Service\"\n  - \"Pod\"\n  - \"ConfigMap\"\n  - \"Secret\"\n  clusters:\n  - \"*\"\n"},"kind":"ConfigMap","metadata":{"annotations":{},"labels":{"app.kubernetes.io/name":"argocd-cm","app.kubernetes.io/part-of":"argocd"},"name":"argocd-cm","namespace":"argocd"}}
  creationTimestamp: "2023-11-07T18:53:33Z"
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
  namespace: argocd
  resourceVersion: "350796"
  uid: 8f1a01f4-d114-44cf-8180-4a21afa35633
