apiVersion: v1
items:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    creationTimestamp: "2023-11-13T19:52:22Z"
    name: argocd-manager-role-binding
    namespace: vault
    resourceVersion: "299929"
    uid: 15740cfe-7242-41a2-aec8-5c0d3af5b791
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: argocd-manager-role
  subjects:
  - kind: ServiceAccount
    name: argocd-manager
    namespace: argocd
kind: List
metadata:
  resourceVersion: ""
